#!/usr/bin/env python

import sys
import os


def path(_):
    return _.strip()

def basename(_):
    return os.path.basename(path(_)).split('-', 1)

def number(_):
    return int(basename(_)[0])

def title(_):
    return basename(_)[1].strip()

def enum(chapters, skip):
    chapters = sorted(chapters, key=lambda f: number(f))
    count = len(chapters) + len(skip)
    magnitude = len(str(count))

    tmps = []

    for i in range(count, 0, -1):
        if i in skip:
            continue

        chapter = src = path(chapters.pop())
        root = os.path.dirname(chapter)
        ix = str(i).zfill(magnitude)
        dest = ix + '-' + title(chapter)
        dest = os.path.join(root, dest)
        tmp = dest + '.moving'
        tmps.append((tmp, dest))
        os.rename(src, tmp)

    # we go through the files in two passes to avoid
    # overwriting existing files
    for tmp, dest in tmps:
        os.rename(tmp, dest)


if __name__ == '__main__':
    skip = map(int, sys.argv[1:])
    chapters = sys.stdin.readlines()
    enum(chapters, skip)

